name: Sonarqube Scan

on: 
  schedule: 
  - cron: '0 0 * * 0'
  push:
    branches: [ 'main' ]

jobs:
  call-sonar-scan:
    name: Call Sonar Scan
    uses: 'bigverl/workflows/.github/workflows/sonar-scan.yml@main'
    with:
      SONAR_PROJECT_NAME: 'BlindChat'
      PYTHON: true
    secrets:
      SONAR_URL: ${{ secrets.SONAR_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
      GHA_PAT: ${{ secrets.GHA_PAT }} 


        