name: Sonarqube Scan

on: 
  schedule: 
  - cron: '0 0 * * 0'
  push:
    branches: [ 'main' ]

jobs:
  call-sonar-scan:
    name: Call Sonar Scan
    uses: 'bigverl/workflows/.github/workflows/sonar-scan.yml@main'
    with:
      SONAR_PROJECT_NAME: 'BlindChat'
      PYTHON_SOURCE_PATH: './'
      PYTHON_TEST_PATH: './test'
      SCAN_ROOT: true 
    secrets:
      SONAR_URL: ${{ secrets.SONAR_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    


        